# This file is a template, and might need editing before it works on your project.
image: valleedelisle/openshift-cli-python

stages:
  - build  # dummy stage to follow the template guidelines
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - staging
  - production
  - cleanup

variables:
  OPENSHIFT_SERVER: https://paas.psi.redhat.com:443
  OPENSHIFT_DOMAIN: paas.psi.redhat.com
  # Configure this variable in Secure Variables:
  # OPENSHIFT_TOKEN: my.openshift.token
test1:
  stage: test
  before_script:
    - python3.6 -m pip install -r requirements.txt
    - python3.6 -m pip install pylint --quiet
    - python3.6 -m pip install pylint-sqlalchemy --quiet
  script:
   - pylint --load-plugins pylint_sqlalchemy oc_mariadb.py bug-report.py hydra-notifierd.py lib/*.py db/* 
  tags:
    - docker

test2:
  stage: test
  before_script:
    - python3.6 -m pip install bandit --quiet
  script:
    - bandit -r bug-report.py hydra-notifierd.py lib/*.py -lll
  tags:
    - docker


.get_oc: &get_oc
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc project "$CI_PROJECT_NAME" 2> /dev/null || oc new-project "$CI_PROJECT_NAME"
 
.clean_env: &clean_env
  script:             
    - oc delete all -l "set=$APP"
    - oc delete secrets -l "set=$APP"
    - oc delete persistentvolumeclaims -l "set=$APP"

.deploy: &deploy
  script:
    - echo "$APP"
    - oc get services "$APP" 2> /dev/null || oc new-app openshift/templates/ess-tools.yaml --name="$APP" -p NAME="$APP" -l "set=$APP" -p SOURCE_REPOSITORY_REF="$CI_COMMIT_REF_NAME"
      #- oc start-build $APP --from-dir=. --follow || sleep 3s && oc start-build $APP --from-dir=. --follow
  tags:
    - docker

review:
  <<: *get_oc
  <<: *clean_env
  <<: *deploy
  stage: review
  variables:
    APP: review-$CI_COMMIT_REF_NAME
    APP_HOST: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$OPENSHIFT_DOMAIN
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$OPENSHIFT_DOMAIN
    on_stop: stop-review
  only:
    - branches
  except:
    - master
  tags:
    - docker

stop-review:
  <<: *get_oc
  <<: *clean_env
  stage: cleanup
  when: manual
  variables:
    APP: review-$CI_COMMIT_REF_NAME
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - docker

staging:
  <<: *get_oc
  <<: *deploy
  stage: staging
  variables:
    APP: staging-ess-notifier
    APP_HOST: $CI_PROJECT_NAME-staging.$OPENSHIFT_DOMAIN
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME-staging.$OPENSHIFT_DOMAIN
  only:
    - master
  tags:
    - docker

clean_staging:
  <<: *get_oc
  <<: *clean_env
  stage: production
  variables:
    APP: staging-ess-notifier
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  when: manual
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master
  tags:
    - docker

rebuild_prod:
  <<: *get_oc
  stage: production
  script:
  - oc start-build ess-notifier --follow
  variables:
    APP: ess-notifier
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  when: manual
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master
  tags:
    - docker
