language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint --quiet
  - pip install bandit --quiet
script:
  - pylint hydra-notifierd.py lib/*.py
  - bandit -r hydra-notifierd.py lib/*.py -lll
