language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint --quiet
  - pip install pylint-sqlalchemy --quiet
  - pip install bandit --quiet
script:
  - pylint --load-plugins pylint_sqlalchemy bug-report.py hydra-notifierd.py lib/*.py db/*.py db/models/*.py
  - bandit -r bug-report.py hydra-notifierd.py lib/*.py db/* -lll
