import smtplib
import traceback
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

class Email():
  def __init__(self, conf, rcpt_to, subject, body_text, body_html=None):
    self.conf = conf
    self.msg = MIMEMultipart('alternative')
    self.msg['From'] = self.conf.notif_email['from']
    self.msg['To'] = rcpt_to
    self.msg['Subject'] = subject
    footer = ("\n\n\nThis notification was automatically generated by the Enhanced Support team.\n" \
                   "Please contact dvd@redhat.com if you need more information\n")
    part1 = MIMEText(body_text + footer, 'plain')
    part2 = MIMEText(body_html + footer.replace("\n", "<br />"), 'html')
    self.msg.attach(part1)
    self.msg.attach(part2)
    try:
      smtp = smtplib.SMTP(self.conf.notif_email['smtp_host'],
                          self.conf.notif_email.getint('smtp_port'))
      smtp.sendmail(msg['From'], msg['To'], msg.as_string())
    except Exception as exc: # pylint: disable=broad-except
      LOG.error("SMTP Failed: %s %s", exc, traceback.format_exc())


