"""
Module for sending emails
"""
import smtplib
import traceback
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import logging

LOG = logging.getLogger("root.mail")

class Email():
  """
  Class to send emails
  """
  # pylint: disable=too-few-public-methods
  def __init__(self, conf, rcpt_to, subject, body_text, body_html=None): # pylint: disable=too-many-arguments
    self.conf = conf
    self.msg = MIMEMultipart('alternative') # pylint: disable=undefined-variable
    self.msg['From'] = self.conf.notif_email['from']
    self.msg['To'] = rcpt_to
    self.msg['Subject'] = subject
    footer = ("\n\n\nThis notification was automatically generated by" \
              "the Enhanced Support team.\n" \
              "Please contact dvd@redhat.com if you need more information\n")
    part1 = MIMEText(body_text + footer, 'plain')  # pylint: disable=undefined-variable
    part2 = MIMEText(body_html + footer.replace("\n", "<br />"), 'html')  # pylint: disable=undefined-variable
    self.msg.attach(part1)
    self.msg.attach(part2)
    try:
      smtp = smtplib.SMTP(self.conf.notif_email['smtp_host'],
                          self.conf.notif_email.getint('smtp_port'))
      smtp.sendmail(self.msg['From'], self.msg['To'], self.msg.as_string())
    except Exception as exc: # pylint: disable=broad-except
      LOG.error("SMTP Failed: %s %s", exc, traceback.format_exc())
